// questions.js - defines all question texts

const questions = [
  { id: "q1",  text: "Are the research objectives clearly stated?" },
  { id: "q2",  text: "Is the study design appropriate for the objectives?" },
  { id: "q3",  text: "Are key variables well defined?" },
  { id: "q4",  text: "Is the sampling method adequately described?" },
  { id: "q5",  text: "Is the data collection process clearly explained?" },
  { id: "q6",  text: "Are ethical issues addressed (e.g., consent, approval)?" },
  { id: "q7",  text: "Is the statistical analysis method appropriate?" },
  { id: "q8",  text: "Are limitations of the study acknowledged?" },
  { id: "q9",  text: "Is there a clear abstract summarizing key findings?" },
  { id: "q10", text: "Does the title accurately reflect the paper content?" },
  { id: "q11", text: "Are references relevant and current?" },
  { id: "q12", text: "Is the introduction logically structured?" },
  { id: "q13", text: "Are inclusion/exclusion criteria well specified?" },
  { id: "q14", text: "Are results presented clearly and completely?" },
  { id: "q15", text: "Are figures/tables appropriate and labeled?" },
  { id: "q16", text: "Is the discussion linked to existing literature?" },
  { id: "q17", text: "Are conclusions justified by the data?" },
  { id: "q18", text: "Is the methodology reproducible by others?" },
  { id: "q19", text: "Are conflicts of interest disclosed?" },
  { id: "q20", text: "Are funding sources transparently reported?" },
  { id: "q21", text: "Is the review protocol registered (if applicable)?" },
  { id: "q22", text: "Is the search strategy adequately reported?" },
  { id: "q23", text: "Is the selection process for studies transparent?" },
  { id: "q24", text: "Are bias risks assessed systematically?" },
  { id: "q25", text: "Are findings synthesized appropriately?" },
  { id: "q26", text: "Is there evidence of methodological triangulation?" },
  { id: "q27", text: "Are qualitative data analyzed rigorously?" },
  { id: "q28", text: "Is the case context described in detail?" },
  { id: "q29", text: "Are citations critically engaged (not just listed)?" },
  { id: "q30", text: "Is the contribution to theory or practice clear?" },
  { id: "q31", text: "Are altmetric impacts discussed or tracked?" },
  { id: "q32", text: "Are semantic keywords present in abstract and title?" },
  { id: "q33", text: "Are citation contexts (supportive/critical) analyzed?" },
  { id: "q34", text: "Does the paper follow ethical publishing norms?" },
  { id: "q35", text: "Are author contributions clearly stated?" },
  { id: "q36", text: "Are software/data/code publicly accessible?" },
  { id: "q37", text: "Are evaluation tools/frameworks declared?" },
  { id: "q38", text: "Are open peer review processes followed?" },
  { id: "q39", text: "Are methods/tools reusable by others?" },
  { id: "q40", text: "Is the paper suitable for informing policy/practice?" }
];
